### ISSUE TITLE
duh-bus not properly installed ERROR while running command duh-portinf

### ISSUE THREAD

**Issue by ishitapvips** [sifive/duhportinf#16]
Hi,
I am trying to run duh-portinf command but it is giving the following error
<pre>Traceback (most recent call last):
  File "/home/ishita/node_modules/.bin/duh-portinf", line 16, in <module>
    duhportinf.main_portinf.main()
  File "/home/ishita/node_modules/duhportinf/pylib/duhportinf/main_portinf.py", line 202, in main
    "duh-bus not properly installed, please use -b/--duh-bus"
AssertionError: duh-bus not properly installed, please use -b/--duh-bus
</pre>

the command was running fine but after installing the newest version of duh-1.16.3 the command is giving above error.
Reverting the previous version of duh gives the same error.

**Comment by Ramlakshmi3733** [comment]
Reproducible but due to issues related to pio.json5
works in other cases.  will root cause and update the ticket.

**Comment by Ramlakshmi3733** [comment]
cleaned and am able to run without trouble.
am closing the ticket as it is highlighting issues with pio.json5 not duhportinf.
If you do not agree, send me a note and i will follow up.
